#!/usr/bin/env bash
#
# Rebuild web/vendor/pano-engine.js — the 360 renderer behind the sphere viewer.
#
# The engine is vendored rather than pulled from a CDN because it is what every
# share link loads, on phones with poor connections, and a third-party outage
# would take every 360 in the product down with it.
#
# It is built from source rather than copied from a release so the global name
# can be set to OrbitPano. That is a build flag, not a patch: the library code
# itself is untouched, which is what keeps this reproducible.
#
# Usage:  scripts/build-pano-engine.sh [path-to-source-checkout]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${1:-${PANO_ENGINE_SRC:-$HOME/marzipano}}"
OUT="$ROOT/web/vendor/pano-engine.js"
VERSION="0.10.2"

if [ ! -f "$SRC/src/index.js" ]; then
  echo "No engine source at $SRC" >&2
  echo "Clone it (github.com/google/marzipano) and pass the path, or set PANO_ENGINE_SRC." >&2
  exit 1
fi

cd "$SRC"
if [ ! -d node_modules ]; then
  echo "==> installing build dependencies"
  npm install --no-audit --no-fund
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# The attribution below is required by the Apache 2.0 licence and must stay,
# including the note about what was changed. Renaming the global is permitted;
# dropping the copyright is not.
cat > "$WORK/preamble.js" <<PREAMBLE
// Orbit panorama engine — the 360 renderer behind Orbit's sphere viewer.
//
// Vendored, minified build. Do not edit this file; rebuild it with
// scripts/build-pano-engine.sh instead.
//
// Exposes a single global: OrbitPano.
//
// ---------------------------------------------------------------------------
// Derived from Marzipano (https://www.marzipano.net), v${VERSION}.
// Copyright 2016 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Changes from upstream: built as a single file and exposed under the global
// name OrbitPano rather than Marzipano. The library code itself is unmodified.
// ---------------------------------------------------------------------------
PREAMBLE

echo "==> bundling"
PATH="node_modules/.bin:$PATH" browserify \
  --noparse='node_modules/**/*.js' \
  -s OrbitPano \
  -o "$WORK/bundle.js" \
  src/index.js

echo "==> minifying"
PATH="node_modules/.bin:$PATH" uglifyjs \
  --compress --mangle \
  -o "$WORK/min.js" \
  "$WORK/bundle.js"

cat "$WORK/preamble.js" "$WORK/min.js" > "$OUT"
cp LICENSE "$ROOT/web/vendor/pano-engine-LICENSE.txt"

echo "==> wrote $OUT ($(du -h "$OUT" | cut -f1))"
